---
baseURL: 'https://marcelorodrigues.dev/'
copyright: '{year}'
languageCode: 'pt-BR'
defaultContentLanguage: 'pt'
theme: 'enchanted-lowkey'
title: 'Marcelo Rodrigues'
enableRobotsTXT: true
summaryLength: 15
pagination:
  pageSize: 5
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: 'dracula'
    tabWidth: 4